language: go
go:
  - 1.9.x
services:
  - mysql
install:
  - mysql -uroot -e "create database threep"  
  - go get github.com/tools/godep
  - go get github.com/mattn/goveralls
script:
  - godep restore
  - make test

after_success:
  - $HOME/gopath/bin/goveralls -v -repotoken LhUNwwyOZBJbLDRI5z2a2Qtx1CJUUQaZh
